export default function handler(req, res) {
  const words = [
    "PODRE", "CASAL", "LIVRO", "FELIZ", "GRATO", "NORTE", "SABER", "TIGRE", "VIRAR", "ZEBRA",
    "SAGAZ", "NEGRO", "TERMO", "ÊXITO", "MEXER", "NOBRE", "SENSO", "AFETO", "ÉTICA", "ALGOZ",
    "PLENA", "FAZER", "ASSIM", "TÊNUE", "MÚTUA", "SOBRE", "VIGOR", "AQUÉM", "SEÇÃO", "PODER",
    "SUTIL", "PORÉM", "FOSSE", "SANAR", "IDEIA", "CERNE", "AUDAZ", "MORAL", "INATO", "DESDE",
    "QUIÇÁ", "MUITO", "JUSTO", "SONHO", "HONRA", "TORPE", "RAZÃO", "AMIGO", "ÍCONE", "FÚTIL",
    "ETNIA", "ÉGIDE", "ANEXO", "TANGE", "DENGO", "HAVER", "LAPSO", "ENTÃO", "EXPOR", "TEMPO",
    "BOÇAL", "SEARA", "HÁBIL", "MÚTUO", "GRAÇA", "ÁVIDO", "ARDIL", "ÓBICE", "DIZER", "XIBIU",
    "PESAR", "DEVER", "ESTAR", "CAUSA", "SENDO", "TENAZ", "PÁRIA", "COSER", "AINDA", "BRADO",
    "GENRO", "CRIVO", "TEMOR", "POSSE", "COMUM", "PROLE", "ÁPICE", "ÂNIMO", "ASSAZ", "CORJA",
    "CEDER", "DETÉM", "PAUTA", "FUGAZ", "CENSO", "ÂNSIA", "CULTO", "DIGNO", "ATROZ", "MUNDO",
    "FORTE", "VULGO", "GLEBA", "VÍCIO", "MESMO", "SAÚDE", "CRIAR", "COZER", "VALHA", "REVÉS",
    "TODOS", "DENSO", "JEITO", "PUDOR", "DOGMA", "NENÉM", "LOUCO", "ATRÁS", "REGRA", "ORDEM",
    "LIMBO", "MERCÊ", "PEDIR", "CLAVA", "HOMEM", "IMPOR", "BANAL", "ROUND", "USURA", "AJUDA",
    "COISA", "JUÍZO", "FORMA", "SÁBIO", "LEGAL", "SERVO", "CERTO", "PROSA", "FALAR", "TENRO",
    "PRESA", "DESSE", "PÍFIO", "POSSO", "FALSO", "CUNHO", "VENDO", "HERÓI", "DEVIR", "VIRIL",
    "ONTEM", "FÁCIL", "MANSO", "VALOR", "VISAR", "MEIGA", "PUDER", "LINDA", "SÉRIO", "ÉBRIO",
    "MÁGOA", "ACASO", "REAÇA", "GUISA", "FLUIR", "AFAGO", "ÍMPIO", "LUGAR", "PLATÔ", "TEMER",
    "ABRIR", "GARBO", "PRAXE", "OBTER", "UNIÃO", "GERAR", "AFINS", "BURRO", "ÓBVIO", "MATIZ",
    "CISMA", "BRUMA", "PLENO", "ÊXODO", "CRISE", "VÊNIA", "TÉDIO", "FLUXO", "SENIL", "HAVIA",
    "ÁLIBI", "RITMO", "MORTE", "LEVAR", "ENFIM", "OLHAR", "TOMAR", "CASTA", "VISÃO", "GÊNIO",
    "PRUMO", "BREGA", "PARVO", "OUVIR", "VITAL", "CABAL", "RELES", "BRAVO", "FALTA", "FAVOR",
    "CALMA", "PARCO", "OUTRO", "PULHA", "VIVAZ", "RETER", "TECER", "SÁBIA", "TERRA", "TENDO",
    "AMENO", "VIVER", "VALIA", "LAICO", "FORÇA", "ÚNICO", "PASSO", "NOÇÃO", "ACHAR", "CARMA",
    "POSSA", "REVER", "NICHO", "RANÇO", "POBRE", "PAPEL", "NOSSA", "NOITE", "FAÇAM", "ROGAR",
    "PRIME", "FARDO", "FARSA", "ATIVO", "DÚBIO", "FATOR", "COESO", "ÉPICO", "SELAR", "ÓBITO",
    "ANELO", "CLARO", "SINTO", "LÍDER", "SESTA", "LEIGO", "CITAR", "CISÃO", "SONSO", "CESTA",
    "DETER", "CIÚME", "VELHO", "ATUAR", "HASTE", "GENTE", "ADIAR", "TENDE", "VAZIO", "REVEL",
    "HUMOR", "FICAR", "SULCO", "IDEAL", "FONTE", "ÁRDUO", "PONTO", "MARCO", "VEMOS", "IGUAL",
    "LABOR", "EXATO", "FEIXE", "AMPLO", "TERNO", "SENÃO", "REMIR", "LAVRA", "HIATO", "TANTO",
    "CAPAZ", "CAUDA", "DÉBIL", "CICLO", "RELVA", "ÓTICA", "INATA", "GESTO", "JOVEM", "VARÃO",
    "AMBOS", "TENRA", "COÇAR", "CHUVA", "IMUNE", "TOADA", "VÁCUO", "RAIVA", "SONSA", "POUCO",
    "APOIO", "CAÇAR", "VELAR", "VIMOS", "SÉRIE", "ALGUM", "XEQUE", "FARÃO", "HORDA", "FEITO",
    "FUSÃO", "ADVÉM", "LEITO", "ENTRE", "COESA", "SENTE", "CARRO", "PROBO", "DOIDO", "MINHA",
    "CRUEL", "TRAMA", "FRASE", "ANUIR", "BRISA", "SORTE", "TORÇO", "LAZER", "ÍMPAR", "VERSO",
    "CHATA", "RIGOR", "MASSA", "BOTAR", "PRECE", "BLASÉ", "MAIOR", "PEGAR", "DORSO", "SEITA",
    "SIGNO", "FAUNA", "MOÇÃO", "PRESO", "FUROR", "COVIL", "CREDO", "CASTO", "FLORA", "MORAR",
    "PLANO", "LIAME", "VETOR", "COMER", "ADEUS", "SAIBA", "AGORA", "OCASO", "PRAIA", "SENDA",
    "DÓCIL", "ÁUREA", "PECHA", "NUNCA", "PESTE", "FAINA", "HOUVE", "ALIÁS", "AMBAS", "ÁRIDO",
    "SETOR", "MANHA", "ARDOR", "MUDAR", "PEIXE", "VÍRUS", "PARTE", "VISSE", "MESES", "REZAR",
    "SALVO", "ANTRO", "VULTO", "BEATA", "RISCO", "PAJEM", "ACESO", "SAÍDA", "BREVE", "VASTO",
    "JUNTO", "MORRO", "ÓTIMO", "CAMPO", "AVARO", "GRUPO", "ESTÃO", "SINAL", "BANZO", "REGER",
    "PRADO", "ANTES", "ÁUREO", "ANDAR", "ANAIS", "LENDA", "SEGUE", "CONTA", "SERÃO", "OPÇÃO",
    "ACIMA", "BIRRA", "CHULO", "OXALÁ", "FUGIR", "MOTIM", "LEITE", "RAPAZ", "VERBO", "VILÃO",
    "FESTA", "NAÇÃO", "BRAVA", "FREIO", "LIVRE", "CÉU", "FALHA", "MORNO", "PENAR", "TURBA", 
    "LÍNGUA", "CÉLERE", "FELINO", "GOLPE", "HABITAR", "ÍNDICE", "JULGAR", "LÂMINA"
  ];
  const randomIndex = Math.floor(Math.random() * words.length);
  res.status(200).json({ word: words[randomIndex] });
}